name: socar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_naver_map: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.otf
          weight: 700
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.otf
          weight: 400

  assets:
    - assets/
