name: socar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # A dd
    sdk: flutter # Add
  flutter_native_splash: ^2.2.7
  provider: ^6.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_naver_map: ^1.0.2
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  intl: ^0.18.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.otf
          weight: 700
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.otf
          weight: 400